baseURL: https://iamleo.space
languageCode: en-us
defaultContentLanguage: en
title: Leonardo Hernández Cano's website
theme: ["hugo-video", "cupper-hugo-theme"]
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Leo's website.
  homeMetaContent: Leo's website.
  footer: '<a rel="me" href="https://mastodon.social/@da_doomer">Mastodon</a> | <a href="mailto: leo@iamleo.space">Email</a> | <a href="https://www.youtube.com/channel/UCLQL3JFR3ugCqELLu4nMA-Q">Youtube</a> | <a href="https://gitlab.com/da_doomer">Gitlab</a> | Made with <a href="https://gohugo.io">Hugo</a> and <a href="https://github.com/zwbetz-gh/cupper-hugo-theme">Cupper</a>.'

  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Leo's website
  # logoAlt: An alternative text description of the logo
  utterances:
    repo: dadoomer/personal-website
    issueTerm: title
    theme: github-light


menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Research
      url: /research/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 4
    - name: About
      url: /about/
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 2
  tableOfContents:
    endLevel: 6
    startLevel: 2




security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
    - ^pandoc$
    osEnv:
    - (?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$
  funcs:
    getenv:
    - ^HUGO_
    - ^CI$
  http:
    methods:
    - (?i)GET|POST
    urls:
    - .*
