baseURL: https://www.iamleo.space
languageCode: en-us
defaultContentLanguage: en
title: Leonardo Hernández Cano's website
theme: ["hugo-video", "cupper-hugo-theme"]
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Computer scientist.
  homeMetaContent: Computer scientist.
  footer: Contact me at leo [at symbol] iamleo dot space
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  katex: true
  hideHeaderLinks: false
  search: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Research
      url: /research/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 4
    - name: About
      url: /about/
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
